Feature/54395 test get leads
FJala-Tr2020/back-end-e1 pull request #7
Opened 2021-07-09 22:51 UTC by christiandp7

Adding Leads endpoint test [GET]

2021-07-15 14:39 UTC, marcelo-yourday requested changes

2021-07-15 14:39 UTC, marcelo-yourday commented on src/index.ts
> +app.get('/leads', async (_req: Request, res: Response): Promise<Response> => {
@christiandp7 if we add all REST API resources and verbs we will have a highly coupled file. Maybe it is worth to try to decouple the service layer. Maybe you can take a look to this:

https://expressjs.com/en/4x/api.html#router

2021-07-20 01:55 UTC, christiandp7 commented on src/index.ts
> +app.get('/leads', async (_req: Request, res: Response): Promise<Response> => {
Thanks @marcelo-yourday The team is already working on this refactor, I'm currently working on Unit Testing files. I'll fix the branch conflict locally and then push the changes.

2021-07-23 14:22 UTC, marcelo-yourday approved these changes

2021-07-23 23:09 UTC, christiandp7 commented
@marcelo-yourday @douglasalizares Please review my latest changes, I've Fixed server.close() and fix some git conflicts.

2021-07-26 15:13 UTC, douglasalizares approved these changes
looks good.

2021-07-26 15:14 UTC, merged