Feature/53892 lead list back end
FJala-Tr2020/back-end-e1 pull request #9
Opened 2021-07-21 23:06 UTC by douglasalizares

Se implementó los end points con tests para la lista de leads

2021-07-22 00:18 UTC, ebrjose approved these changes
Looks good..

2021-07-22 14:37 UTC, marcelo-yourday requested changes

2021-07-22 14:37 UTC, marcelo-yourday commented on src/controllers/lead/leadDtoBuilder.ts
> +    return this.leads.map(() => {
I think an easier way to do it is:

```javascript
return this.leads.map((lead) => ({
  contactName: lead.contactName, 
  email: lead.email,
  phone: lead.phone
});
```

2021-07-22 14:37 UTC, marcelo-yourday commented on src/data/iLeadRepository.ts
> +  getAllLeads(): Lead[];
You can use a better abstraction for a Repository:

```javascript
interface IRepository<ModelType> {
  getAll(): ModelType[];
}
```

2021-07-22 14:37 UTC, marcelo-yourday commented on src/dto/leadDtoJsonFile.ts
> +export interface Lead {
I'm not sure if the name of this file is accurate, it seems we are defining a Lead, so, better if the file is called: lead.ts

2021-07-22 19:39 UTC, douglasalizares commented on src/controllers/lead/leadDtoBuilder.ts
> +    return this.leads.map(() => {
solved

2021-07-22 20:11 UTC, douglasalizares commented on src/data/iLeadRepository.ts
> +  getAllLeads(): Lead[];
resolved

2021-07-22 20:26 UTC, douglasalizares commented on src/dto/leadDtoJsonFile.ts
> +export interface Lead {
Resolved

2021-07-23 14:22 UTC, marcelo-yourday approved these changes

2021-07-23 17:46 UTC, merged